modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "harderdiesel"
version = "1.2.0"
displayName = "Create: Harder Diesel"
description = '''Adds a realistic oil refining chain: 6 crude grades (sweet/sour) by biome, distillation, sour naphtha/kerosene hydrotreating, gasoline/diesel/nitro fuels, vacuum residue cracking into vacuum gas oil.'''
authors = "cacagd22811"

[[mixins]]
config = "harderdiesel.mixins.json"

[[dependencies.harderdiesel]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.harderdiesel]]
modId = "create"
type = "required"
versionRange = "[6.0.7,6.1.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.harderdiesel]]
modId = "createdieselgenerators"
type = "required"
versionRange = "[1.21.1-1.3.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.harderdiesel]]
modId = "jei"
type = "optional"
versionRange = "[19.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.harderdiesel]]
modId = "xaeroszones"
type = "optional"
versionRange = "[2.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.harderdiesel]]
modId = "xaeroworldmap"
type = "optional"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.harderdiesel]]
modId = "xaerominimap"
type = "optional"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "CLIENT"
